/*
 * Here comes the text of your license
 * Each line should be prefixed with  * 
 */
package View.GUI;
import deepspace.EnemyToUI;
/**
 *
 * @author yabir
 */
public class EnemyStarshipView extends javax.swing.JPanel {

    /**
     * Creates new form EnemyStarshipView
     */
    
    LootView lootView;
    DamageView damageView;
    
    public EnemyStarshipView() {
        initComponents();
        
        lootView = new LootView();
        damageView = new DamageView();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EnemyName = new javax.swing.JLabel();
        AmmoPower = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Loot = new javax.swing.JPanel();
        Damage = new javax.swing.JPanel();

        EnemyName.setText("Nombre:");

        AmmoPower.setText("Potencia de fuego:");

        jLabel1.setText("Potencia de defensa:");

        Loot.setBorder(javax.swing.BorderFactory.createTitledBorder("Botin"));

        Damage.setBorder(javax.swing.BorderFactory.createTitledBorder("Daño "));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Loot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EnemyName)
                            .addComponent(AmmoPower)
                            .addComponent(jLabel1))
                        .addGap(0, 251, Short.MAX_VALUE))
                    .addComponent(Damage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(EnemyName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AmmoPower)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(Loot, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Damage, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setEnemy(EnemyToUI e){
        AmmoPower.setText(Float.toString(e.getAmmoPower()));
        EnemyName.setText(e.getName());
        
        damageView.setDamage(e.getDamage());
        lootView.setLoot(e.getLoot());
        
        Loot.add(lootView);
        Damage.add(damageView);
        
        repaint();
        revalidate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AmmoPower;
    private javax.swing.JPanel Damage;
    private javax.swing.JLabel EnemyName;
    private javax.swing.JPanel Loot;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
