/*
 * Here comes the text of your license
 * Each line should be prefixed with  * 
 */
package View.GUI;
import View.View;
import deepspace.GameUniverse;
import java.util.ArrayList;
import controller.Controller;
import javax.swing.JOptionPane;
/**
 *
 * @author yabir
 */
public class MainWindow extends javax.swing.JFrame implements View{
    
    static Controller controller;
    private String appName = "Deepspace";
    private SpaceStationView StationView;
    private EnemyStarshipView EnemyView;
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        
        StationView = new SpaceStationView();
        EnemyView = new EnemyStarshipView();
        
        stationPanel.add(StationView);
        enemyPanel.add(EnemyView);
        
        repaint();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stationPanel = new javax.swing.JPanel();
        enemyPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 720));

        stationPanel.setPreferredSize(new java.awt.Dimension(600, 480));
        stationPanel.setRequestFocusEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(enemyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enemyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public String getAppName(){
        return appName;
    }
    
    @Override 
    public ArrayList<String> getNames() {
        Names namesCapture = new Names (this);
        return namesCapture.getNames();
    }
    
    @Override
    public void showView() {
        setVisible(true);
    }
    
    @Override
    public void updateView() {
        StationView.setSpaceStation(controller.getUIversion().getCurrentStation());
        EnemyView.setEnemy(controller.getUIversion().getCurrentEnemy());
    }
    
    @Override
    public void setController (Controller c) {
        controller = c;
    }
    
    @Override
    public boolean confirmExitMessage() {
        return (JOptionPane.showConfirmDialog(this, "¿Estás segur@ que deseas salir?", getAppName(), JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel enemyPanel;
    private javax.swing.JPanel stationPanel;
    // End of variables declaration//GEN-END:variables
}
